services:
  blog:
    build:
      context: .
    tty: true
    volumes:
      - ./src:/app

    # 環境ファイルを読み込み (https://docs.docker.jp/compose/environment-variables.html)
    working_dir: "/app/${PROJECT_NAME}"
    command: sh -c "npm run dev"
    ports:
      - "15000:3000"